name: openfold-env 
channels:
  - conda-forge
  - bioconda
  - pytorch
  - nvidia 
dependencies:
  - conda-forge::python=3.10
  - conda-forge::libgcc=7.2
  - conda-forge::setuptools=73.0.1
  - conda-forge::pip=24.2
  - cudatoolkit=11.8
  - pytorch::pytorch-cuda=11.8
  - nvidia/label/cuda-11.8.0::cuda-nvcc
  - conda-forge::openmm=7.7
  - pytorch::pytorch=2.4.1
  - pytorch::torchaudio=2.4.1
  - pytorch::torchvision=0.19.1
  - pytorch::torchdata=0.8.0
  - pytorch-lightning=2.4.0
  - conda-forge::pdbfixer
  - pytorch-lightning
  - conda-forge::biopython=1.84
  - conda-forge::dm-tree=0.1.6
  - conda-forge::numpy=1.26
  - conda-forge::pandas=2.2.2
  - conda-forge::PyYAML==5.4.1
  - conda-forge::requests=2.32.3
  - conda-forge::scipy=1.14.1
  - conda-forge::tqdm==4.62.2
  - conda-forge::typing-extensions=4.12.2
  - conda-forge::modelcif==0.7
  # - awscli # use AWS installer
  - ml-collections=0.1.1
  - mkl=2023.0
  # - aria2 # optional
  - git
  # - bioconda::hmmer    # build from src
  # - bioconda::hhsuite  # build from src
  # - bioconda::kalign2  # build from src
  - pip:
      - deepspeed==0.14.4
      - git+https://github.com/NVIDIA/dllogger.git
      - flash-attn==2.6.3
      - wandb==0.12.0
